//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidzyDatabaseFirst.Model
{
    using System;
    
    public enum Classification : byte
    {
        Gold = 0,
        Silver = 1,
        Bronze = 2
    }
}
